### ISSUE TITLE
Essential kit login page not show action bar.

### ISSUE THREAD

**Issue by SurajMazumdar** [syncfusion/essential-ui-kit-for-xamarin.forms#17]
![Screenshot_2019-10-15-11-17-37-26_a4923ac26ab81fdfa157d9039633272e](https://user-images.githubusercontent.com/33419692/66804419-086fc980-ef40-11e9-81f6-f41a50d6f4f7.png)

**Comment by MeikandaNayanar** [comment]
Hi @SurajMazumdar 
Thank you for contacting us.
I hope you have deployed the page on the Android device. We have not exposed the Navigation bar at the top in any of our screens to get more customization options. You can edit the below to code snippet in the XAML page to reset the navigation bar. 	
NavigationPage.HasNavigationBar="False"
Also, let us know if you have any questions further. 
Thanks
Meikandan

**Comment by SurajMazumdar** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="App1.Views.Login.SimpleLoginPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:border="clr-namespace:Syncfusion.XForms.Border;assembly=Syncfusion.Core.XForms"
    xmlns:buttons="clr-namespace:Syncfusion.XForms.Buttons;assembly=Syncfusion.Buttons.XForms"
    xmlns:control="clr-namespace:App1.Controls"
    xmlns:converter="clr-namespace:App1.Converters"
    xmlns:core="clr-namespace:Syncfusion.XForms.Core;assembly=Syncfusion.Core.XForms"
    xmlns:local="clr-namespace:App1.Views.Login"
    xmlns:viewModel="clr-namespace:App1.ViewModels.Login"
    BackgroundColor="{DynamicResource Gray-200}"
    NavigationPage.HasNavigationBar="False">

    <ContentPage.Resources>
        <ResourceDictionary>
            <converter:BooleanToColorConverter x:Key="ColorConverter" />
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="Styles.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </ContentPage.Resources>

    
    <ContentPage.BindingContext>
        <viewModel:LoginPageViewModel />
    </ContentPage.BindingContext>

    <ContentPage.Content>
        <ScrollView HorizontalOptions="Center">
            <ScrollView.VerticalOptions>
                <OnIdiom
                    x:TypeArguments="LayoutOptions"
                    Default="CenterAndExpand"
                    Phone="FillAndExpand" />
            </ScrollView.VerticalOptions>

            <StackLayout
                Margin="{core:OnPlatformOrientationThickness PhonePortrait='20,32',
                                                             PhoneLandscape='150,32',
                                                             TabletPortrait='200,50',
                                                             TabletLandscape='300,50',
                                                             Desktop='30'}"
                Spacing="0"
                VerticalOptions="FillAndExpand"
                WidthRequest="{OnPlatform Default='-1',
                                          UWP='350'}">

                <Grid RowSpacing="0" VerticalOptions="CenterAndExpand">

                    <Grid.RowDefinitions>
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                        <RowDefinition Height="Auto" />
                    </Grid.RowDefinitions>

                    
                    <Label
                        FontFamily="{StaticResource Montserrat-SemiBold}"
                        FontSize="20"
                        HorizontalTextAlignment="Center"
                        Style="{StaticResource LabelStyle}"
                        Text="Log In"
                        TextColor="{DynamicResource Gray-900}" />

                    
                    <Label
                        Grid.Row="1"
                        Margin="0,8"
                        FontFamily="{StaticResource Montserrat-Medium}"
                        HorizontalTextAlignment="Center"
                        Style="{StaticResource LabelStyle}"
                        Text="Let's get to work"
                        TextColor="{DynamicResource Gray-800}" />

                    
                    <local:SimpleEmailEntry Grid.Row="2" Padding="0,24" />

                    
                    <border:SfBorder
                        Grid.Row="3"
                        BackgroundColor="{DynamicResource Gray-White}"
                        BorderColor="{Binding Source={x:Reference PasswordEntry}, Path=IsFocused, Converter={StaticResource ColorConverter}, ConverterParameter=3}"
                        Style="{StaticResource SfBorderStyle}">
                        <control:BorderlessEntry
                            x:Name="PasswordEntry"
                            IsPassword="True"
                            Placeholder="Password"
                            PlaceholderColor="{DynamicResource Gray-700}"
                            Style="{StaticResource EntryStyle}"
                            Text="{Binding Password}"
                            TextColor="{DynamicResource Gray-900}" />
                    </border:SfBorder>

                    
                    <Label
                        x:Name="ForgotPasswordLabel"
                        Grid.Row="4"
                        Margin="0,16"
                        FontFamily="{StaticResource Montserrat-SemiBold}"
                        FontSize="12"
                        HorizontalOptions="End"
                        Text="FORGOT PASSWORD?"
                        TextColor="{DynamicResource Gray-800}">
                        <Label.GestureRecognizers>
                            <TapGestureRecognizer Command="{Binding ForgotPasswordCommand}" CommandParameter="{x:Reference ForgotPasswordLabel}" />
                        </Label.GestureRecognizers>
                    </Label>

                    
                    <buttons:SfButton
                        Grid.Row="5"
                        Margin="0,16"
                        Command="{Binding LoginCommand}"
                        Style="{StaticResource SfButtonStyle}"
                        Text="LOG IN" />


                    <Label
                        Grid.Row="6"
                        FontFamily="{StaticResource Montserrat-Medium}"
                        HorizontalTextAlignment="Center"
                        Style="{StaticResource LabelStyle}"
                        Text="Or create an account using social media"
                        TextColor="{DynamicResource Gray-800}" />

                    
                    <buttons:SfButton
                        Grid.Row="7"
                        Margin="0,16,0,16"
                        BackgroundColor="{DynamicResource FacebookBlue}"
                        Command="{Binding SocialMediaLoginCommand}"
                        CornerRadius="20"
                        HeightRequest="40">
                        <buttons:SfButton.Content>
                            <StackLayout
                                HorizontalOptions="CenterAndExpand"
                                Orientation="Horizontal"
                                VerticalOptions="Center">
                                <Label
                                    FontFamily="{StaticResource FontIcons}"
                                    FontSize="18"
                                    Text="&#xe735;"
                                    TextColor="{DynamicResource Gray-White}"
                                    VerticalTextAlignment="Center" />
                                <Label
                                    FontFamily="{StaticResource Montserrat-Medium}"
                                    FontSize="16"
                                    Text="Login with Facebook"
                                    TextColor="{DynamicResource Gray-White}" />
                            </StackLayout>
                        </buttons:SfButton.Content>
                    </buttons:SfButton>

                </Grid>

                <StackLayout
                    HorizontalOptions="Center"
                    Orientation="Horizontal"
                    Spacing="1"
                    VerticalOptions="End">

                    <StackLayout.Padding>
                        <OnIdiom
                            x:DataType="Thickness"
                            Default="0, 48, 0, 0"
                            Phone="0" />
                    </StackLayout.Padding>

                    <Label
                        FontFamily="{StaticResource Montserrat-Medium}"
                        HorizontalOptions="CenterAndExpand"
                        HorizontalTextAlignment="Center"
                        Style="{StaticResource LabelStyle}"
                        Text="Don't have an account?"
                        TextColor="{DynamicResource Gray-900}"
                        VerticalTextAlignment="Center" />

                    
                    <buttons:SfButton
                        Command="{Binding SignUpCommand}"
                        CornerRadius="4"
                        Style="{StaticResource SfFlatButtonStyle}"
                        Text="Sign Up" />

                </StackLayout>

            </StackLayout>
        </ScrollView>
    </ContentPage.Content>

</ContentPage>

**Comment by SurajMazumdar** [comment]
<ContentPage
    x:Class="App1.Views.Login.SimpleLoginPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:border="clr-namespace:Syncfusion.XForms.Border;assembly=Syncfusion.Core.XForms"
    xmlns:buttons="clr-namespace:Syncfusion.XForms.Buttons;assembly=Syncfusion.Buttons.XForms"
    xmlns:control="clr-namespace:App1.Controls"
    xmlns:converter="clr-namespace:App1.Converters"
    xmlns:core="clr-namespace:Syncfusion.XForms.Core;assembly=Syncfusion.Core.XForms"
    xmlns:local="clr-namespace:App1.Views.Login"
    xmlns:viewModel="clr-namespace:App1.ViewModels.Login"
    BackgroundColor="{DynamicResource Gray-200}"
    NavigationPage.HasNavigationBar="False">

**Comment by SurajMazumdar** [comment]
![image](https://user-images.githubusercontent.com/33419692/66894870-19d3d700-f00f-11e9-94ec-48054f43af89.png)

**Comment by MeikandaNayanar** [comment]
Hi @SurajMazumdar 

Please change the below highlighted in your SimpleLoginPage.xaml page.

![image](https://user-images.githubusercontent.com/44013602/66895080-95ce1f00-f00f-11e9-9969-8f8e1ac98a4f.png)

Please let us know if this doesn't meet your requirements. 

Thanks,
Meikandan

**Comment by SurajMazumdar** [comment]
Hi @MeikandaNayanar 

Thank you for replying me. Actully i want to rounded action bar like below image

![image](https://user-images.githubusercontent.com/33419692/66896040-c616bd00-f011-11e9-8c80-c2bf0528d0be.png)

and my code is 

![image](https://user-images.githubusercontent.com/33419692/66896157-ee062080-f011-11e9-82e3-e7f1c9347ad2.png)

**Comment by SurajMazumdar** [comment]
also tried NavigationPage.HasNavigationBar="False" but not show rounded corner 

thanks.

**Comment by YuvarajPalanisamy** [comment]
Hi Suraj,

To customize the NavigationBar we have disabled the inbuilt NavigationBar and added a StackLayout to replace its appearance and used the SfBorder control for the rounded corners. We have created a simple sample for your requirement and attached the sample in below link.

[Simple Sample ](https://www.syncfusion.com/downloads/support/directtrac/251819/ze/Sample-1575572777)

Please let us know whether this suits your requirement.

Thanks
Yuvaraj

**Comment by MeikandaNayanar** [comment]
Hi @SurajMazumdar 

I hope the sample, we have provided meets your requirements and closing this thread now. 

Please let me know if you have any questions about this, also do not hesitate to open a new thread if you face any issues.

Thanks
Meikandan
