### ISSUE TITLE
Dashboards

### ISSUE THREAD

**Issue by nm-a** [syncfusion/essential-ui-kit-for-xamarin.forms#19]
Hi Team,
Thank you for very handy & useful kit. I see developers spend lot of time to develop beautiful dashboards / landing pages. 

If possible can you add few dashboards to this kit. 

thank you

**Comment by MeikandaNayanar** [comment]
Hi There,

Thank you for reaching out to us.

Yes, we are planning to a few dashboard screens to UI Kit like ‘Stock Analysis’ and ‘Whether Broadcasting’ but not yet finalized. Do you have any specific dashboard suggestions to do?

Please let me know if you have any questions,

Thanks
Meikandan

**Comment by nm-a** [comment]
Thank you @MeikandaNayanar ,

I feel we can start with simple dashboards which can be used in Line of Business  applications. Few screenshots as per my knowledge

https://www.figmacrush.com/mobile-dashboard-template-figma/
https://www.pinterest.com/pin/130885932904051598/
https://grialkit.com/portfolio-items/employee-performance-dashboard-page/
https://dribbble.com/shots/7173092-Crypto-Currency-App-Dashboard-Wallet


thank you

**Comment by MeikandaNayanar** [comment]
Hi @nm-a 

Thank you for your suggestions. 

We will consider these references while implementing the dashboard screens. We can expect the dashboard screens by end of December 2019.

Thanks,
Meikandan
