### ISSUE TITLE
Chat text box behaviour hides all text when you have multiple lines

### ISSUE THREAD

**Issue by developer9969** [syncfusion/essential-ui-kit-for-xamarin.forms#24]
Hi there
I think your app looks really good and fantastic!
However it would be nice if the text box in chat conversation would be standard in behavior like what's up -iOS -Android.

Basically if you type on multiple lines the text gets hidden , in all those applications when you type text in multiple lines the text box expands and you can see all the text.

Can this be achieved with syncfusion controls?
thanks

**Comment by YuvarajPalanisamy** [comment]
Hi, 

We tried with the below sample and we cannot reproduce the mentioned issue at our end. We suspect that to resolve this by updating the Syncfusion.Xamarin.SfListView version. Please try the sample below and let us know if you could still reproduce the same issue.

Sample :  [ChatConversationSample.zip](https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/files/3814066/ChatConversationSample.zip)


Regards,
Yuvaraj

**Comment by developer9969** [comment]
Thank you for your prompt response and for your sample. Yes your version works as expected!!

**Comment by MeikandaNayanar** [comment]
Thank you for the confirmation @developer9969 . We are glad that the solution worked at your end.
