### ISSUE TITLE
Please update to latest version, also onboarding screen alternate design not available

### ISSUE THREAD

**Issue by SailorTurkey** [syncfusion/essential-ui-kit-for-xamarin.forms#25]
Hello, you have updated ui kit to 2.2.0 but marketplace still has 2.1.0 version.
Also from screenshots i can see there is an alternate onboarding design, where skip/next buttoms are bottom left/right respectively, but via toolkit its not possible to use that template, see:

[https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/blob/master/Images/xamarin-forms-ui-template-onboarding-screen.jpg](https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/blob/master/Images/xamarin-forms-ui-template-onboarding-screen.jpg)

**Comment by MeikandaNayanar** [comment]
Hi @Sailor

Thank you for contacting us.

**You have updated UI kit to 2.2.0 but the marketplace still has 2.1.0 version.**

Yes, we have done some template changes to remove the duplicate views, so updated it alone in GitHub. We will update these changes in our next Visual Studio extension marketplace release, expected to be available by the mid of Nov 2019.

 **I can see there is an alternate onboarding design**.

We have this Onboarding screen in our roadmap, but not yet published. 

Please let us know if you have any further questions.

Thanks,
Meikandan
