### ISSUE TITLE
How use async method in constructor of view model

### ISSUE THREAD

**Issue by MHKarami97** [syncfusion/essential-ui-kit-for-xamarin.forms#31]
Hi. How we can use async method for example to call httpClient in view model init?
Please add example of it (I want to use refit) also userDialog in code.

**Comment by YuvarajPalanisamy** [comment]
Hi Mohammad Hossein Karami,

Thank you for contacting us.

We have prepared a sample as per your requirement with async method in view model constructor. Please find the sample from the below location.

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample-799489922 
 
Please let us know if you have any concern.

Regards,
Yuvaraj

**Comment by MeikandaNayanar** [comment]
Hi @MHKarami97 

I hope the updated sample suites your requirements. We are closing this ticket now, please feel free to open a new thread for any other requirements or queries.

Thanks
Meikandan
