### ISSUE TITLE
Is not adding pages in project

### ISSUE THREAD

**Issue by artur309** [syncfusion/essential-ui-kit-for-xamarin.forms#32]
Im trying add pages on my project and isn´t adding

**Comment by YuvarajPalanisamy** [comment]
Hi Artur Quaresma

Thank you for contacting us.

Can you please provide to us the following details which will be helpful to serve you better solution.
•	Please let us know how the UI Kit Pages were added? Whether you are using the 'Visual Studio Extension for Syncfusion Essential UI Kit Xamarin.Forms or Paste UI Kit pages directly from the location of GitHub.
•	Also please let us know what Pages you want to add to your application.
•	OS: Mac or Windows

Regards,
Yuvaraj

**Comment by artur309** [comment]
1º using Visual Studio Extension for Syncfusion Essential UI Kit Xamarin.Forms
2º Trying to add Social Profile with Interest Page and Settings Page
3º Windows; 
4º Using Visual Studio 2019

**Comment by YuvarajPalanisamy** [comment]
Hi Artur Quaresma,

We regret for your inconvenience. 

We have checked the query, but we are afraid, that we are not able to reproduce the problem [ page not adding in project] at our end. 

Alternatively, we found the BorderlessEntry.cs [https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/blob/master/EssentialUIKit/Controls/BorderlessEntry.cs] file missing issue while adding Settings page via UIKit Extension. 

And now we are checking this issue with high priority and we will let you know the status on or before 23rd January 2020.

Also please revert us the Error Log file [ which is generated in the root folder of your application] for your reported problem, which will be helpful for us to give better solution.

Regards,
Yuvaraj
