### ISSUE TITLE
Syncfusion License popup on app load

### ISSUE THREAD

**Issue by lynx-ralph** [syncfusion/essential-ui-kit-for-xamarin.forms#35]
I'm getting a license popup when loading the login page. 
Isn't this essential-ui-kit completely open source with no need of license? 

i'm on win10, visual studio 2019. 
thanks!

![image](https://user-images.githubusercontent.com/35732591/73600099-d481d980-4519-11ea-8e72-ba8dcca72e7c.png)

**Comment by MuneeshKumarG** [comment]
Hi lynx-ralph,
 
Thank you for contacting us.

We regret your disappointment. But please find the details about the Essential UI Kit license as below. 
 
We have published the Essential UI Kit source code in GitHub with an MIT license. You can use this UI Kit pages in your application without any restrictions.  But for the pages that use Syncfusion controls, you must get the license to use those controls in your application. The Syncfusion provides free community licenses that provide free access to all the Syncfusion products for individual developers and small businesses. (updated the links below to know more about the Syncfusion free community licenses).  

Alternatively, you can replace the Syncfusion controls with the framework controls and use them to avoid getting any licenses. 
https://www.syncfusion.com/feedback/xamarin-forms
 
For more details about the Essential UI Kit license, please refer https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms#license 
 
Regarding the Syncfusion licenses, please refer to https://www.syncfusion.com/sales/licensing. 
 
To know more about the Syncfusion community licenses, please refer https://www.syncfusion.com/products/communitylicense  
 
Please let us know if you need any further assistance in this.  
 
Thanks
Muneesh Kumar G
