### ISSUE TITLE
installed syncfusion extension are not showing up in VS 2019 for Mac

### ISSUE THREAD

**Issue by ahmarz** [syncfusion/essential-ui-kit-for-xamarin.forms#40]
I did a fresh new install for VS 2019 for mac and followed your documentation but the installed syncfusion extension are not showing up in VS 2019 for Mac...

**Comment by MuneeshKumarG** [comment]
Hi Ahmarz,

Greetings from Syncfusion.

We have analyzed your reported problem, and could you please check whether created Xamarin.Forms project have the Xamarin.Forms NuGet package since we are enabling the Syncfusion Essential UI Kit option when the project have the Xamarin.Forms NuGet package. 

If your Xamarin project does not have Xamarin.Forms NuGet, please install the Xamarin.Forms NuGet package in your machine and try to use the Syncfusion Essential UI Kit using Syncfusion UI Kit documentation. 

If still you are facing the issue, could you please update the below details to check the issue from our side. 

1.	Check whether the Syncfusion Essential UI Kit Visual Studio extension is installed or not from the Extension Manager dialog.
2.	Screenshot for the reported issue.
3.	Share the IDE.log file. Get this file by follow the steps form the below link.
            https://docs.microsoft.com/en-us/visualstudio/mac/troubleshooting?view=vsmac-2019#viewing-logs-in-visual-studio-for-mac 

Thanks,
Muneesh Kumar G.

**Comment by ahmarz** [comment]
I installed two versions:

1.Syncfusion.Xamarin.Mac.UIKit_1.0.0.0.mpack
2.Syncfusion.Xamarin.Mac.UIKit_2.5.0.0.mpack

both 1 and 2 display the same issue with VS 2019 for mac, they simply donot integrate although they report that they are correctly installed as extensions and yes i have restarted VS 3 times :)

also i have followed your documentation here:
https://help.syncfusion.com/xamarin/uikit/gettingstarted?_ga=2.133742222.1653685436.1581865891-47378656.1581865891

Could you just tell me from where i can download this file "Syncfusion Xamarin VS Mac Extensions.mpack" and i have listed the mpack files that i could download.. and yes the Prjoect is Xamarin.Forms and yes i have NuGet.

Please send a more descriptive reply with links and sources of the mpack files

**Comment by MuneeshKumarG** [comment]
Hi Ahmarz,

Syncfusion Xamarin.Forms UI Kit
 
Currently Syncfusion Xamarin controls supports to the NETStandard Xamarin Forms project only and not supported in the Shared library project. If you are using the Shared library Xamarin Forms project, the essential UI kit option will not show to add the Syncfusion Xamarin control pages to your project. So, please create the new NETStandard Xamarin Forms project and try to use the Syncfusion Essential UI kit. 

Syncfusion Xamarin Project Template
  
But checking your updated screenshot, we suspect that you have installed the Syncfusion Essential UI kit which is used for add the Syncfusion Xamarin controls page in your Xamarin Forms project. But you are trying to find the Syncfusion Xamarin project template in the New project dialog. If you want to use the Syncfusion Xamarin project template in Visual Studio 2019 Mac to create the new Syncfusion Xamarin project, please follow the steps from the below links. 
  
Extension Installation: https://help.syncfusion.com/xamarin/visual-studio-integration/visual-studio-mac-extensions/installation 
Syncfusion Xamarin Project Template: https://help.syncfusion.com/xamarin/visual-studio-integration/visual-studio-mac-extensions/create-project 
 
Also, currently we are providing the Syncfusion UI kit and Syncfusion Project Template extension support for Xamarin.Forms. To develop the Xamarin Forms using these extensions, you need to install the below mpack files in your Visual Studio.  

  
UIKit: https://cdn.syncfusion.com/essential-ui-kit-for-xamarin.forms/Syncfusion.Xamarin.Mac.UIKit_2.5.0.0.mpack?_ga=2.119144841.1621146489.1581913172-412525225.1559890194 

Project Template:  Follow the below steps, 
  
1.	Download the Syncfusion Xamarin Mac setup from here.
2.	Extract the zip file and get the Syncfusion.Xamarin.VSMac.VSExtension.mpack file from the below location.
            <Zip Extract location>\Xamarin\Extension\ Syncfusion.Xamarin.VSMac.VSExtension.mpack. 
 
Thanks,
Muneesh Kumar G.

**Comment by MeikandaNayanar** [comment]
Hi @ahmarz 

We will update you in this thread once we have implemented your requirements. We are closing this ticket now, please feel free to open a new thread for any other requirements or queries.

Thanks
Meikandan
