### ISSUE TITLE
User recognized row and actual row are difference.

### ISSUE THREAD

**Issue by jz5** [syncfusion/essential-ui-kit-for-xamarin.forms#45]
ListView (SfListView.ItemTemplate) has divider (aka sepalator, delimiter).
This trick has problems.
User recognized row and actual row are difference.
This induces tap mistakes.
And can't use SelectionBackgroundColor (except for transparent)
And can't use ripple effect (v17.4.0.50. SfListView bugfix #263112)

![IMG_2388](https://user-images.githubusercontent.com/435620/77719216-19ad1e00-7028-11ea-81cd-d844f3fcda3d.jpg)
Navigation/Song

**Comment by MuneeshKumarG** [comment]
Hi Jz5,

Greetings from Syncfusion,

We have analyzed your requirement and you can achieve this by changing Margin value for grid and Size for image as per the below code snippet. 

``

<listView:SfListView.ItemTemplate>
    <DataTemplate>
     <ViewCell>
      <StackLayout >
       <Grid Margin="16,10,16,5" RowSpacing="0" ColumnSpacing="0" HeightRequest="56">
        <Grid.ColumnDefinitions>
         <ColumnDefinition Width="Auto" />
         <ColumnDefinition Width="*" />
        </Grid.ColumnDefinitions>
       <border:SfBorder BackgroundColor="{DynamicResource Gray-200}"
                        BorderColor="{DynamicResource Gray-Bg}"
                        Style="{StaticResource ProfileBorderStyle}">
        <Image HeightRequest="50" WidthRequest="48">
          <Image.Source>
              <UriImageSource CacheValidity="14"                                                             
                              CachingEnabled="true"
                              Uri="{Binding SongImage}"/>
                      </Image.Source>
         </Image>
       </border:SfBorder>
     <StackLayout   Grid.Column="1" Margin="16,0" HorizontalOptions="FillAndExpand"
                    Spacing="0" VerticalOptions="Center">

                                                
         <Label 
FontFamily="{StaticResource Montserrat-Medium}" FontSize="16"
            LineHeight="{OnPlatform Android=1.5,
              Default=-1}"
             Text="{Binding SongName}"
             TextColor="{DynamicResource Gray-900}" />

                                                
          <Label
FontFamily="{StaticResource Montserrat-Medium}"
              FontSize="14"
              LineHeight="{OnPlatform Android=1.25,
                                                         Default=-1}"
                                                      Text="{Binding Composer}"
              TextColor="{DynamicResource Gray-700}" />
       </StackLayout>
     </Grid>

   <BoxView  VerticalOptions="End" Style="{StaticResource BoxViewStyle}" />
        </StackLayout>
      </ViewCell>
    </DataTemplate>
   </listView:SfListView.ItemTemplate>

Thanks,
Muneesh Kumar G

**Comment by jz5** [comment]
Thank you. It's good. 
I hope you fix this problem for the templates and the VS extension.

**Comment by MuneeshKumarG** [comment]
Hi Jz5,

Thanks for your reply. 

We did not have selection support for most of the screens designed with list items. We will solve this problem with complete testing in any of our release.

Thanks,
Muneesh Kumar G.

**Comment by MeikandaNayanar** [comment]
Hi @jz5 

We will update you in this thread once we have implemented your requirements. We are closing this ticket now, please feel free to open a new thread for any other requirements or queries. 

Thanks
Meikandan
