### ISSUE TITLE
Github code pages are not identical with code pages added by VS Extension.

### ISSUE THREAD

**Issue by volkan-akkus-tr** [syncfusion/essential-ui-kit-for-xamarin.forms#46]
![1](https://user-images.githubusercontent.com/56273545/78546543-46bab700-7806-11ea-923e-72fefd7c27d5.png)
![2](https://user-images.githubusercontent.com/56273545/78546548-491d1100-7806-11ea-81ca-632fd032408c.png)

As far as I understand, the extension don't add updated code for some pages. Some other pages are also missing completely.

I would like to read your comments. Thank you.

Here is what I did.

I have created a new Xamarin Forms project, added all avaliable pages via the extension, 
named "Essential UI Kit for Xamarin.Forms" and located at 
https://marketplace.visualstudio.com/items?itemName=SyncfusionInc.Essential-UI-Kit-Xamarin-Forms

I have compared solution folders with comparison tool called WinMerger loated at winmerge.org 

I have added two images.

**Comment by YuvarajPalanisamy** [comment]
Hi Volkan,

Greetings from Syncfusion.

We have analyzed your query and we would like to inform you that the reported missing images related with our old screen pages, already we have plan to do complete testing in our next upcoming release. Which will be expected to publish on or before end of April, 2020. The reported problem will be resolved in this release. 

Regards,
Yuvaraj

**Comment by HemalathaMarikuma-syncfusion** [comment]
Hi @volkan-akkus-tr ,

The release of UIKit was postponed until the end of January 2021. Until then, we appreciate your patience.

Regards,
Hemalatha M.

**Comment by MeikandaNayanar** [comment]
Hi @volkan-akkus-tr 

We are happy to announce that we have completed our recent 4.0.0 release in GitHub and Visual Studio extensions. 

Please let us know if you have any questions.

Thanks
Meikandan
