### ISSUE TITLE
Looking for Info

### ISSUE THREAD

**Issue by abdielcorda** [syncfusion/essential-ui-kit-for-xamarin.forms#47]
Hi, can you guys share the source/site for this SVG image?

**Comment by OmayMomay** [comment]
![image](https://user-images.githubusercontent.com/28887426/80588703-692da200-8a4b-11ea-9b64-c9d58db7ed7c.PNG)

**Comment by AnandRaj32** [comment]
Hi @OmayMomay ,

Please have the source code for SVG in Essential UIKit Xamarin.

https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/blob/master/EssentialUIKit/Controls/SVGImage.cs

**Comment by OmayMomay** [comment]
> Hi @OmayMomay ,
> 
> Please find the source code for displaying the SVG image in the Essential UIKit project below.
> 
> https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/blob/master/EssentialUIKit/Controls/SVGImage.cs
> 
> Thanks
> Meikandan

Hi, yep already got the image. I was hoping if where i can find source/site for more Images needed. Like (i) for Info

**Comment by MeikandaNayanar** [comment]
Hi @abdielcorda 

We regret the delayed reply. 

You can find the SVG images used in this project from here.

https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/tree/master/EssentialUIKit/Images

These images created for this project and we cannot find these SVG images elsewhere. 

Please let us know if you need any further assistance in this.

Thanks
Meikandan
