### ISSUE TITLE
Essential UI kit License

### ISSUE THREAD

**Issue by abenzakour** [syncfusion/essential-ui-kit-for-xamarin.forms#49]
Hi, 

First of all; I thank you for this perfect work that helps us as developers to make good quality applications.

I have a question about this project license: 

![image](https://user-images.githubusercontent.com/3093754/83508434-d8226e80-a4c1-11ea-98d8-d6190f30b5f6.png)

Based on the MIT License; we are able to use Essential UI KIT free of charge

But when I clone it using git and open it using Visual studio 2019 and try to run it on android

I get a 30 days trial version? Can you explain to me how can I use it without having this pop-up ?

![image](https://user-images.githubusercontent.com/3093754/83509072-c68d9680-a4c2-11ea-8a8a-63d168200925.png)

**Comment by MeikandaNayanar** [comment]
Hi @abenzakour ,

Please find more details about the licence of Xamarin UI Kit from the below documentation link.

https://help.syncfusion.com/xamarin/uikit/licensing

Please let us know if you need any assistance in this.

Thanks
Meikandan

**Comment by abenzakour** [comment]
Perfect; 
Thank you
