### ISSUE TITLE
sf:Button throws Exception in SignUpPage.xaml

### ISSUE THREAD

**Issue by dgerding** [syncfusion/essential-ui-kit-for-xamarin.forms#50]
Hi,
I get a runtime exception* when trying to switch to the SignUpPage in my app via:

`await Shell.Current.GoToAsync("//appStarting/signUp")`

I get the same failure using all the different types of XF navigation/page load I could try, but I need to use Shell.

_However_, if I replace the reference to sf:Button (the one bound to SignUpCommand) with a regular Xamarin Forms button the page works and will load.

_Any_ effort to include an sf:Button on the generated xaml produces the error, but only at runtime and only at the last moment when the page is loaded/go-to'd etc..

Thanks,
Dave G

*System.Reflection.TargetInvocationException
  Message=Exception has been thrown by the target of an invocation.

**Comment by HemalathaMarikuma-syncfusion** [comment]
Could you please clear the cache and then check it.

https://www.syncfusion.com/kb/6987/how-to-clear-nuget-cache

**Comment by jsypolt** [comment]
I just came across this and am seeing  exactly the same problem and exception

When navigating with Shell via a command from SfButton I get the same exception. If I clear the Xaml on the destination page leaving only an empty layout such as StackLayout or ScrollLayout in ContentPage.Content then it works. I can even put the Xaml controls back after the destination loads and hot reload works fine. But not if Sf controls are present in the destination Xaml when the page loads. 

Xamarin Forms 5.0.0.1931
Syncfusion.Xamarin.* 18.4.0.35

**Comment by cjkarande** [comment]
Same here...i to am seeing the same error "System.Reflection.TargetInvocationException Message=Exception has been thrown by the target of an invocation." 

Additionally the log shows "[TabLayout] MODE_SCROLLABLE + GRAVITY_FILL is not supported, GRAVITY_START will be used instead". So possibly the issue seems to be with syncfusion TabLayout or TabView.

Can anyone throw some light on this...?
