### ISSUE TITLE
How about the pull request and some updates ?

### ISSUE THREAD

**Issue by stephenhauck** [syncfusion/essential-ui-kit-for-xamarin.forms#51]
This needs to be updated, I downloaded it and it does not build correctly and I see there is a pull request pending.
Can we check the pull and update this project ?

**Comment by MeikandaNayanar** [comment]
Hi Stephen,
Can you please let us know what kind of problem you are facing while building the project? So that we can assist you better with an appropriate solution.  Regarding the pull request, it is not complete, there are few other updates we are making for the next release which we are planning for this month-end. 
Please let us know if you need any other assistance in this.
Thanks
Meikandan

**Comment by stephenhauck** [comment]
Forget it ... you guys are always “month end”, that pull request was made a lot th a go or more

**Comment by stephenhauck** [comment]
1>------ Rebuild All started: Project: EssentialUIKit, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\3.1.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(257,5): warning NETSDK1023: A PackageReference for 'NETStandard.Library' was included in your project. This package is implicitly referenced by the .NET SDK and you do not typically need to reference it from your project. For more information, see https://aka.ms/sdkimplicitrefs
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\AppLayout\Views\TemplateHostPage.xaml.g.cs(26,45,26,50): warning CS0108: 'TemplateHostPage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\Controls\CountryComboBox.cs(193,50,193,65): warning CS0108: 'CountryComboBox.PropertyChanged' hides inherited member 'BindableObject.PropertyChanged'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Catalog\ArticleCardPage.xaml.g.cs(26,51,26,56): warning CS0108: 'ArticleCardPage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Catalog\EventListPage.xaml.g.cs(26,51,26,56): warning CS0108: 'EventListPage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Dashboard\DailyCaloriesReportPage.xaml.g.cs(23,57,23,62): warning CS0108: 'DailyCaloriesReportPage.Scale' hides inherited member 'VisualElement.Scale'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Detail\DataTablePage.xaml.g.cs(23,51,23,56): warning CS0108: 'DataTablePage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Settings\HelpPage.xaml.g.cs(26,51,26,56): warning CS0108: 'HelpPage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Navigation\DocumentsListPage.xaml.g.cs(23,51,23,56): warning CS0108: 'DocumentsListPage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Navigation\FAQPage.xaml.g.cs(26,51,26,56): warning CS0108: 'FAQPage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Navigation\FileExploreGridPage.xaml.g.cs(23,51,23,56): warning CS0108: 'FileExploreGridPage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Navigation\FileExploreListPage.xaml.g.cs(23,51,23,56): warning CS0108: 'FileExploreListPage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Navigation\IconNamesListPage.xaml.g.cs(23,51,23,56): warning CS0108: 'IconNamesListPage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Navigation\MoviesListPage.xaml.g.cs(23,51,23,56): warning CS0108: 'MoviesListPage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Navigation\NamesListPage.xaml.g.cs(23,51,23,56): warning CS0108: 'NamesListPage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Navigation\RestaurantPage.xaml.g.cs(23,51,23,56): warning CS0108: 'RestaurantPage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Navigation\SelectableNamePage.xaml.g.cs(23,51,23,56): warning CS0108: 'SelectableNamePage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Navigation\SongsPage.xaml.g.cs(23,51,23,56): warning CS0108: 'SongsPage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Navigation\SongsPlayListPage.xaml.g.cs(23,51,23,56): warning CS0108: 'SongsPlayListPage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\obj\Debug\netstandard2.0\Views\Navigation\SuggestionPage.xaml.g.cs(23,51,23,56): warning CS0108: 'SuggestionPage.Title' hides inherited member 'Page.Title'. Use the new keyword if hiding was intended.
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\AppLayout\Views\TemplatePage.xaml.cs(102,13,102,104): warning CS0618: 'Device.OpenUri(Uri)' is obsolete: 'OpenUri is obsolete as of version 4.3.0. Use Launcher.OpenAsync (or CanOpenAsync, or TryOpenAsync) from Xamarin.Essentials instead.'
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\AppLayout\Views\HomePage.xaml.cs(155,13,155,104): warning CS0618: 'Device.OpenUri(Uri)' is obsolete: 'OpenUri is obsolete as of version 4.3.0. Use Launcher.OpenAsync (or CanOpenAsync, or TryOpenAsync) from Xamarin.Essentials instead.'
1>C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\ViewModels\Catalog\CategoryPageViewModel.cs(22,25,22,41): warning CS0169: The field 'CategoryPageViewModel.expandingCommand' is never used
1>EssentialUIKit -> C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit\bin\Debug\netstandard2.0\EssentialUIKit.dll
1>Done building project "EssentialUIKit.csproj".
2>------ Rebuild All started: Project: EssentialUIKit.Android, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: EssentialUIKit.iOS, Configuration: Debug iPhoneSimulator ------
4>------ Rebuild All started: Project: EssentialUIKit.UWP, Configuration: Debug x86 ------
3>  Executing SayHello Task to establish a connection to a Mac Server. 
3>  						 Properties: SessionId=168178ae6c1d59689035deffbd1f0931, 
3>  							ServerPort=56638, 
3>  							ServerAddress=192.168.5.194, 
3>  							ServerUser=StephenHauck, 
3>  							ServerPassword=, 
3>  							SSHKey=, 
3>  							SSHPassPhrase=,
3>  							AppName=EssentialUIKit.iOS,
3>  							ContinueOnDisconnected=False
4>C:\Users\Stephen\.nuget\packages\xamarin.forms\4.8.0.1269\buildTransitive\Xamarin.Forms.targets(233,5): warning : Xamarin.Forms recommends TargetPlatformVersion >= 10.0.17763.0 (current project is 16299)
4>  EssentialUIKit.UWP -> C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit.UWP\bin\x86\Debug\EssentialUIKit.UWP.exe
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(1307,3): warning : A 1024x1024 app store icon is required for iOS apps
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(1307,3): warning : The app icon set "AppIcon" has 15 unassigned children.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(1307,3): warning : The file "Icon1024.png" for the image set "AppIcon" does not exist.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(1307,3): warning : The app icon set "AppIcon" has 15 unassigned children.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(1307,3): warning : The file "Icon1024.png" for the image set "AppIcon" does not exist.
2>  EssentialUIKit.Android -> C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit.Android\bin\Debug\EssentialUIKit.Android.dll
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/Splash.png obj/iPhoneSimulator/Debug/optimized/Splash.png 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 "Resources/Splash@2x.png" "obj/iPhoneSimulator/Debug/optimized/Splash@2x.png" 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 "Resources/Splash@3x.png" "obj/iPhoneSimulator/Debug/optimized/Splash@3x.png" 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 "Resources/Splash~ipad.png" "obj/iPhoneSimulator/Debug/optimized/Splash~ipad.png" 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/About.png obj/iPhoneSimulator/Debug/optimized/About.png 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/OurTeam.png obj/iPhoneSimulator/Debug/optimized/OurTeam.png 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/HeaderTriangle.png obj/iPhoneSimulator/Debug/optimized/HeaderTriangle.png 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/InvertedTriangle.png obj/iPhoneSimulator/Debug/optimized/InvertedTriangle.png 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 "Resources/LoginBackground~ipad.png" "obj/iPhoneSimulator/Debug/optimized/LoginBackground~ipad.png" 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/LoginBackground.png obj/iPhoneSimulator/Debug/optimized/LoginBackground.png 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 "Resources/LoginBackground@2x.png" "obj/iPhoneSimulator/Debug/optimized/LoginBackground@2x.png" 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 "Resources/LoginBackground@3x.png" "obj/iPhoneSimulator/Debug/optimized/LoginBackground@3x.png" 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 "Resources/LoginBackground@2x~ipad.png" "obj/iPhoneSimulator/Debug/optimized/LoginBackground@2x~ipad.png" 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 "Resources/LoginBackground@3x~ipad.png" "obj/iPhoneSimulator/Debug/optimized/LoginBackground@3x~ipad.png" 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/LoginBackground-Landscape.png obj/iPhoneSimulator/Debug/optimized/LoginBackground-Landscape.png 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 "Resources/LoginBackground-Landscape~ipad.png" "obj/iPhoneSimulator/Debug/optimized/LoginBackground-Landscape~ipad.png" 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 "Resources/LoginBackground-Landscape@2x.png" "obj/iPhoneSimulator/Debug/optimized/LoginBackground-Landscape@2x.png" 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 "Resources/LoginBackground-Landscape@2x~ipad.png" "obj/iPhoneSimulator/Debug/optimized/LoginBackground-Landscape@2x~ipad.png" 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 "Resources/LoginBackground-Landscape@3x.png" "obj/iPhoneSimulator/Debug/optimized/LoginBackground-Landscape@3x.png" 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 "Resources/LoginBackground-Landscape@3x~ipad.png" "obj/iPhoneSimulator/Debug/optimized/LoginBackground-Landscape@3x~ipad.png" 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 "Resources/LoginBackground@4x.png" "obj/iPhoneSimulator/Debug/optimized/LoginBackground@4x.png" 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 "Resources/LoginBackground-Landscape@4x.png" "obj/iPhoneSimulator/Debug/optimized/LoginBackground-Landscape@4x.png" 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/ChatMessageBackground.png obj/iPhoneSimulator/Debug/optimized/ChatMessageBackground.png 
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(1148,3): warning : Warning: Input PNG does not have an 8 bit input depth.  Please convert your PNG to 8-bit for optimal performance on iPhone OS.
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/Card.png obj/iPhoneSimulator/Debug/optimized/Card.png 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/Close.png obj/iPhoneSimulator/Debug/optimized/Close.png 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/Pin.png obj/iPhoneSimulator/Debug/optimized/Pin.png 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/PlaceHolder.png obj/iPhoneSimulator/Debug/optimized/PlaceHolder.png 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/PlaceHolderRectangle.png obj/iPhoneSimulator/Debug/optimized/PlaceHolderRectangle.png 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/HeaderIcon.png obj/iPhoneSimulator/Debug/optimized/HeaderIcon.png 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/ReSchedule.png obj/iPhoneSimulator/Debug/optimized/ReSchedule.png 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/TimeZone.png obj/iPhoneSimulator/Debug/optimized/TimeZone.png 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/ViewMode.png obj/iPhoneSimulator/Debug/optimized/ViewMode.png 
3>  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush -q -iphone -f 0 Resources/Visa.png obj/iPhoneSimulator/Debug/optimized/Visa.png 
3>  Consider app.config remapping of assembly "SkiaSharp, Culture=neutral, PublicKeyToken=0738eb9f132ed756" from Version "1.60.0.0" [] to Version "2.80.0.0" [C:\Users\Stephen\.nuget\packages\skiasharp\2.80.1\lib\xamarinios1.0\SkiaSharp.dll] to solve conflict and get rid of warning.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.
3>  EssentialUIKit.iOS -> C:\Users\Stephen\Downloads\essuiSF\EssentialUIKit.iOS\bin\iPhoneSimulator\Debug\EssentialUIKit.iOS.exe
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Xamarin.Apple.Sdk.targets(144,3): warning : [xma]: A problem occurred while using the SCP Client. Trying again with a new SCP connection...
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Xamarin.Apple.Sdk.targets(144,3): warning : Message type 52 is not valid in the current context.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Xamarin.Apple.Sdk.targets(144,3): warning :    at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout) in C:\Git\SSH.NET\src\Renci.SshNet\Session.cs:line 906
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Xamarin.Apple.Sdk.targets(144,3): warning :    at Renci.SshNet.Session.Renci.SshNet.ISession.WaitOnHandle(WaitHandle waitHandle) in C:\Git\SSH.NET\src\Renci.SshNet\Session.cs:line 768
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Xamarin.Apple.Sdk.targets(144,3): warning :    at Renci.SshNet.Channels.Channel.WaitOnHandle(WaitHandle waitHandle) in C:\Git\SSH.NET\src\Renci.SshNet\Channels\Channel.cs:line 511
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Xamarin.Apple.Sdk.targets(144,3): warning :    at Renci.SshNet.Channels.ChannelSession.Open() in C:\Git\SSH.NET\src\Renci.SshNet\Channels\ChannelSession.cs:line 79
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Xamarin.Apple.Sdk.targets(144,3): warning :    at Renci.SshNet.ScpClient.Upload(Stream source, String path) in C:\Git\SSH.NET\src\Renci.SshNet\ScpClient.cs:line 217
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Xamarin.Apple.Sdk.targets(144,3): warning :    at Xamarin.Messaging.Ssh.MessagingScpClient.<>c__DisplayClass17_0.<UploadAsync>b__0(ScpClient client) in C:\A\_work\80\s\External\messaging\src\Xamarin.Messaging.Ssh\MessagingScpClient.cs:line 73
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Xamarin.Apple.Sdk.targets(144,3): warning :    at Xamarin.Messaging.Ssh.MessagingScpClient.<ExecuteAsync>d__23.MoveNext() in C:\A\_work\80\s\External\messaging\src\Xamarin.Messaging.Ssh\MessagingScpClient.cs:line 153
3>  Detected signing identity:
3>          
3>    Bundle Id: com.syncfusion.EssentialUIKit
3>    App Id: com.syncfusion.EssentialUIKit
3>  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/stephenhauck/Library/Caches/Xamarin/mtbs/builds/EssentialUIKit.iOS/168178ae6c1d59689035deffbd1f0931/obj/iPhoneSimulator/Debug/response-file.rsp 
========== Rebuild All: 4 succeeded, 0 failed, 0 skipped ==========

**Comment by tanczosm** [comment]
I can confirm that this does not build out of the box.

**Comment by MeikandaNayanar** [comment]
Hi @tanczosm / @stephenhauck 

We are glad to inform you that we have recently merged our 4.0.0 release updates in this repository and we hope this will resolve the above issue. 

Please let us know if you need any assistance with this. 

Thanks
Meikandan
