### ISSUE TITLE
Cannot compile the package after update to Visual Studio 2019 16.7.2

### ISSUE THREAD

**Issue by psun888** [syncfusion/essential-ui-kit-for-xamarin.forms#54]
The error shows like this:
Your project does not reference "MonoAndroid,Version=v10.0" framework. Add a reference to "MonoAndroid,Version=v10.0" in the "TargetFrameworks" property of your project file and then re-run NuGet restore.	EssentialUIKit.Android

**Comment by YuvarajPalanisamy** [comment]
Hi,

We have analyzed your query and we have checked with same version visual studio 2019 16.7.2 and it was working fine at our end. We would like to discuss more about your issue, so please share your licensing details to support@syncfusion.com mail id, which will be helpful for us to proceed further.

Regards,
Yuvaraj

**Comment by HemalathaMarikuma-syncfusion** [comment]
Hi @psun888,

As we have not heard from you since our last update, we are proceeding to mark this as closed. Please get back to us with more requested details.

Regards,
@HemalathaMarikuma-syncfusion

**Comment by HemalathaMarikuma-syncfusion** [comment]
@psun888 ,

As we have not heard from you since our last update, we are proceeding to mark this as closed. Please get back to us with more requested details.

Regards,
Hemalatha M.
