### ISSUE TITLE
UIFontIcons.ttf Update Process

### ISSUE THREAD

**Issue by luis-cortina** [syncfusion/essential-ui-kit-for-xamarin.forms#57]
Hi:

I want to add some icons to this file but it would be great to have specifics in terms of icons used, configurations and in general how to update this file.

Thanks,

Luis

**Comment by YuvarajPalanisamy** [comment]
Hi Luis,  
   
Greetings from Syncfusion. 
 
For your information, most of the web tools to enhance the icons support are not supporting to edit the existing ttf/otf file to include desired icons. In case of urgency, please share your desired icons file as ai or SVG, we will work for you and update. 
   
Regards, 
Yuvaraj

**Comment by luis-cortina** [comment]
Here are the ones I would like.
[Desktop.zip](https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/files/5495850/Desktop.zip)

**Comment by YuvarajPalanisamy** [comment]
Hi Luis,

Thanks for your patience.

As per your requirement, we have included the provided font icons in our existing font icon file (UIFontIcons.ttf). Please fine that from the below link. 

[FontIcon](https://www.syncfusion.com/downloads/support/directtrac/general/ze/FontIcon-251344362 )

Regards,
Yuvaraj
