### ISSUE TITLE
View is available on the screenshots but not in the Extension

### ISSUE THREAD

**Issue by cornelha** [syncfusion/essential-ui-kit-for-xamarin.forms#58]
The following view is shown in the screenshots but nowhere to be found in the Extension or in the repo
![image](https://user-images.githubusercontent.com/1282205/97612937-b6052c00-1a20-11eb-831d-66619f70aec7.png)

**Comment by cornelha** [comment]
Bump, this is urgent I need help with this layout today.

**Comment by YuvarajPalanisamy** [comment]
Hi Cornelha, 
 
Greetings!  We would like to let you know that mentioned interest template still in the process of designing. To know the exact timeline and tracking link for knowing this implementation status, please share your information to support@syncfusion.com mail id. 

Regards,
Yuvaraj
