### ISSUE TITLE
Schedule Related

### ISSUE THREAD

**Issue by dayAndnight2018** [syncfusion/essential-ui-kit-for-xamarin.forms#60]
Is there any schedule about cross platform design especially for macbook? Or is there any schedule to support "Avalonia" project?

**Comment by YuvarajPalanisamy** [comment]
Hi, 
  
Greetings from Syncfusion. 
  
Currently, we don’t have any plans to integrate Syncfusion controls (Syncfusion Xamarin.Forms Essential UI Kit implemented involves the usage of Syncfusion controls) in Avalonia platform. 
 
Please let us know if you need any other assistance. 

Regards,
Yuvaraj.

**Comment by dayAndnight2018** [comment]
> Hi,
> 
> Greetings from Syncfusion.
> 
> Currently, we don’t have any plans to integrate Syncfusion controls (Syncfusion Xamarin.Forms Essential UI Kit implemented involves the usage of Syncfusion controls) in Avalonia platform.
> 
> Please let us know if you need any other assistance.
> 
> Regards,
> Yuvaraj.

ok, thanks
