### ISSUE TITLE
License

### ISSUE THREAD

**Issue by omiddehghan2036** [syncfusion/essential-ui-kit-for-xamarin.forms#62]
Is this project free?

**Comment by MHKarami97** [comment]
https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/blob/master/LICENSE

This project is in MIT license, but syncfusion is not free.

https://www.syncfusion.com/sales/products

**Comment by MeikandaNayanar** [comment]
Hi @omiddehghan2036 ,

We have published the Essential UI Kit source code on GitHub with an MIT license. You can use these UI Kit pages in your application for free without any restrictions. 

But for the pages that use Syncfusion controls, you must get the licenses to use those controls in your application to avoid the license validation pop-ups. Syncfusion provides free community licenses that provide access to all the Syncfusion products for individual developers and small businesses. (updated the links below to know more about the Syncfusion free community licenses).

Alternatively, you can replace the Syncfusion controls with the framework controls and use them to avoid getting any licenses.

For more details about the Essential UI Kit license, please refer

https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/blob/master/LICENSE

Regarding the Syncfusion licenses, please refer

https://www.syncfusion.com/sales/licensing

To know more about the Syncfusion community licenses, please refer

https://www.syncfusion.com/products/communitylicense

Please let us know if you need any further assistance in this.

Thanks

Meikandan

**Comment by omiddehghan2036** [comment]
Thanks
I Use this project but the pop-up license page is repeated in the app every time. How can i fix it ?
https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms

**Comment by HemalathaMarikuma-syncfusion** [comment]
Duplicate issue task of https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/issues/64, hence closing

**Comment by SwingsetTheory** [comment]
This issue entry has a more helpful explanation that #64 does, IMHO the #64 should be closed and this one kept open.

Question: how do I know which controls are Syncfusion controls? If I want to use the UI templates and replace the controls with Xamarin.Forms controls, how do I identify the code that needs to be replaced?

**Comment by MeikandaNayanar** [comment]
Hi @SwingsetTheory ,

The Syncfusion community licenses do not expire. Companies and individuals with less than $1 million USD in annual gross revenue and 5 or fewer developers are eligible to get the community license. You will continue to receive support and updates for new versions. Please refer to the below documentation to know more about the Syncfsuion community license.

https://www.syncfusion.com/products/communitylicense

 **How do I know which controls are Syncfusion controls?** 

You can identify the Syncfusion controls by removing the references to the Syncfusion packages from the projects. 

Please let us know if you need any further assistance in this.

Thanks
Meikandan
