### ISSUE TITLE
Error on creating View from UI Extension

### ISSUE THREAD

**Issue by juanredondo** [syncfusion/essential-ui-kit-for-xamarin.forms#65]
The IU Extension Wizard drops an error to an file the second time you use it (creating Chat Views) on the same project:

`Date:2021-01-22 11:25:42,083
Thread:[1]
Level:ERROR
Logger:Syncfusion.Xamarin.UI.MainViewModel                         [(null)]
Message:Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode+ProjectWizardException (0x80004005): Fail to run wizard 'c:\users\jredondo\appdata\local\microsoft\visualstudio\16.0_94dff4f7\extensions\contwm35.jbf\ItemTemplates\CSharp\Chat Message\Chat Message.vstemplate'.
Message: Referencia a objeto no establecida como instancia de un objeto. ---> System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.
   en Microsoft.VisualStudio.TemplateWizard.Wizard.EnumContentsAddItem(ProjectItems projectItems, XmlNode contentNode, String projectName, String currentFolder, String currentTargetFolder, String rootName, String templateFolderPath, String destinationRootFolderPath, String userSpecifiedDestItemPath, String projectTypeString, List`1 wizardExtensions, String rootExtension)
   en Microsoft.VisualStudio.TemplateWizard.Wizard.Execute(Object application, Int32 hwndOwner, Object[]& ContextParams, Object[]& CustomParams, wizardResult& retval)
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   en Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.RunWizard(SimpleHierarchyNode parentNode, String itemName, String wizardToRun, IntPtr dlgOwner)
   en Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<AddItemWithSpecificAsync>d__612.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.<>c__DisplayClass1_0.<<AddFromTemplate>b__0>d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.<>c__DisplayClass72_0`1.<<Mutate>b__0>d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass569_0.<<Mutate>b__0>d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   en Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(Func`1 asyncAction)
   en Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.Mutate(Func`1 asyncAction, Boolean includesFileSystemChange, String telemetryActivity)
   en Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.Mutate[T](Func`1 asyncAction, Boolean includesFileSystemChange, String telemetryActivity)
   en Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItems.AddFromTemplate(String fileName, String name)
   en Syncfusion.Xamarin.UI.MainWindow.AddItem_Click(Object sender, RoutedEventArgs e)`

**Comment by GanesanRengasamy** [comment]
Hi Juanredondo,

We have checked the Syncfusion Essential UI kit from our side, and we are not able to reproduce the reported issue from our side. Please share the below details to check the issue further from our side. 

1.	Reproducing steps with screenshot.
2.	What are the pages you have added before adding the chat page in your application?
3.	In which Xamarin project (like Xamarin.Forms, Xamarin.Forms.Android, Xamarin.Forms.iOS, Xamarin.Forms.UWP) you have tried the Essential UI kit to add the Syncfusion Xamarin pages?
4.	Which Syncfusion Essential UI kit version you have installed in your machine?

Regards,
Ganesan Rengasamy.

**Comment by juanredondo** [comment]
Hi Ganesan, 
1. Screenshots:
![image](https://user-images.githubusercontent.com/7248837/105699220-4b706900-5f07-11eb-9bda-aca91d10d5ab.png)
2. No other pages added to the project. The complete process was: add the Chat view on my xamarin.forms project. This adds with no problem to the iOS one too. By mistake, the UWP and Android one was not loaded in VS2019, so I discard changes on GIT, load both project, android and UWP, run again the wizard and the error appears.
3. I have been tried on a Xamarin.Forms project, with depending Android, iOs and UWP projcets
4. Version 3.0.0.0

**Comment by GanesanRengasamy** [comment]
Hi Juanredondo,

We have followed the steps which you have to reproduce the issue but still we are not able to reproduce the reported issue from our side. Please share the below details also to check the issue.

1.	Share sample application if you have faced the issue in the new Xamarin application else Xamarin project files (*csproj) if you have faced this issue in your development application.
2.	Which Visual Studio 2019 version you are using for development?

Regards,
Ganesan Rengasamy.
