### ISSUE TITLE
187 build errors from login page!

### ISSUE THREAD

**Issue by SwingsetTheory** [syncfusion/essential-ui-kit-for-xamarin.forms#67]
I built a brand-new project in Visual Studio for the Mac, and I added the Login page from the Essentials menu.

I get this:

<img width="1134" alt="Screen Shot 2021-02-25 at Feb 25  4 03 35 pm" src="https://user-images.githubusercontent.com/4856483/109217061-51b26900-7783-11eb-9ad7-c5422dd468b8.png">

I have tried many many things to solve this, and no matter what I do it just gives me a different kind of error.

So I'm going back to the first error messages that appeared; these are they.

All 187 are similarly trivial-seeming things, and none of these errors are actually evident in the LightTheme.xaml file. That file looks perfect--so perfect in fact, that there are no red compiler errors marked anywhere on the screen.

**Comment by YuvarajPalanisamy** [comment]
Hi,

Greetings from Syncfusion.

We have analyzed your query and we have prepared the sample with SimpleLoginPage in visual studio for MAC with the help of Syncfusion Xamarin.Forms Essential UIKit extension and it was working fine at our end. Please find the sample from the below link.

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/SimpleLoginPageSample1222767180 

Also, you can get the UI Kit visual studio extension for Windows and MAC from the below link.
https://www.syncfusion.com/essential-xamarin-ui-kit 

For more details please refer the below link
https://help.syncfusion.com/xamarin/uikit/gettingstarted 

If still you are facing the problem could you please share your configuration details of Visual studio for MAC which will helpful to serve you better solution at the earliest.

Regards,
Yuvaraj

**Comment by SwingsetTheory** [comment]
Attachment available until Mar 28, 2021
Hello Yuvaraj,

Thank you for your timely reply.

I very much appreciate the sample project you made, it does run perfectly, and I am very confused why my own test fails so miserably.

Here is a very simple and short video of me creating a new project, adding a gradient login, and getting over a hundred errors when I try to run it:

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAeHuHhnkLzSYu3IoSsTKTwRDEBCUAdxxgV8V85xsZhb6Daz9uB2O-qhV%2F%24%7Bf%7D%3Fo%3DAkXiPlV-oUED4FP3Kf7vpVLsbksQVDqG-egKqiVj6psE%26v%3D1%26x%3D3%26a%3DCAogVCSToe3EkEyhl4WRSwdBaEd_Oc7Ap0Nnb_SBqwOWN4ISdhDP6tv8_S4Yz_rW0IcvIgEAKgkC6AMA_0I9S_dSBEMQEJRaBI76qFVqJWM8KvpeAh49zEr5IbBJdoEEyKWhcohKfoWhdTZ4IOm8eLtgbcVyJfhp6QFTWqmT4mcXmwWPen6GAeDpUwSfUQmuJXHMp_tIfKdF338%26e%3D1616955948%26fl%3D%26r%3D01CD50AA-5692-4DF8-97A9-B4A8A60DE002-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D56A3EF25-3914-4603-9C51-B7FEFD85FFFB%26p%3D44%26s%3DrqMMPHIaq0cBJXlYLxQxRI-uhNk&uk=cdZQsH7gmCpL4sEXudPMfg&f=GradientLogin%20Fail.mp4&sz=44356294>GradientLogin Fail.mp4
44.4 MB

To keep the file size down it is a little fuzzy, but if you look closely you can see exactly what the error messages are.

As to the configuration details, since there are about a jillion different settings in Visual Studio, can you be more specific about what you need to see?

Thanks for any help you can give,

—Jesse

**Comment by YuvarajPalanisamy** [comment]
Hi,

The Xamarin.Forms Syncfusion Essential UI Kit supports iOS 9.0 and later versions. We suspect that your project application having lesser than the iOS version 9.0. To resolve this problem, Kindly update the iOS version. 

For more details, please refer the below link.
[https://help.syncfusion.com/xamarin/uikit/overview](https://help.syncfusion.com/xamarin/uikit/overview) 

Please let us know if you have any version.

Regards,
Yuvaraj.
