### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by nm-a** [syncfusion/essential-ui-kit-for-xamarin.forms#8]
Please add .gitignore file, it will help developers while exploring.

thank you

**Comment by MeikandaNayanar** [comment]
Hi @nm-a 

Thank you for contacting us.

We have now added the  .gitignore file with this [pull request](https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/pull/9).

Thanks,
Meikandan
