### ISSUE TITLE
Where are the images in the Article List and other views

### ISSUE THREAD

**Issue by IDispose** [syncfusion/essential-ui-kit-for-xamarin.forms#88]
I see the binding `imagePath=` in the view model but I cannot find the bound image in the `Images` folder. Where are the images that load in various views? For example the images in `sfRotator`

**Comment by RajaRamalingam3772** [comment]
We are retrieving images from a URI and displaying them in our app by storing the images in a specific location and using a static string to reference that location in our code.

```
//App.xaml.cs file

public static string ImageServerPath { get; } = "[https://cdn.syncfusion.com/essential-ui-kit-for-xamarin.forms/common/uikitimages/"](https://cdn.syncfusion.com/essential-ui-kit-for-xamarin.forms/common/uikitimages/%22);
```
Additionally, we are organizing view data in .json files, such as the [catalog.json](https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/blob/master/EssentialUIKit/Data/catalog.json) file, which is used to populate the rotator in the [ArticleListPage](https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/blob/master/EssentialUIKit/Views/Catalog/ArticleListPage.xaml#L95). The corresponding [model](https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/blob/master/EssentialUIKit/Models/Story.cs) and [view model](https://github.com/syncfusion/essential-ui-kit-for-xamarin.forms/blob/master/EssentialUIKit/ViewModels/Catalog/ArticleListViewModel.cs#L59) files have also been configured to map json variables to the appropriate properties.

![MicrosoftTeams-image (41)](https://user-images.githubusercontent.com/105496256/210778944-8547bf55-8324-41c7-a059-60ed49956173.png)

Once value assigned from json data, the ImageServePath and image path makes complete uri to fetch image from our storage server.
